{
 "title": "Application",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "ParticipantName",
    "query": "label_values(dds_domain_participant_remote_participant_count, participant_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Topics",
     "type": "table",
     "description": "Shows the topics with serialized sizes",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "max(dds_topic_type_serialized_size_bytes{participant_name=\"$ParticipantName\"}) by (topic_name, type_name)"
      },
      {
       "expr": "max(dds_data_writer_serialized_sample_min_size_bytes{participant_name=\"$ParticipantName\"}) by (topic_name, type_name)"
      },
      {
       "expr": "max(dds_data_writer_serialized_sample_max_size_bytes{participant_name=\"$ParticipantName\"}) by (topic_name, type_name)"
      },
      {
       "expr": "max(dds_data_writer_serialized_key_max_size_bytes{participant_name=\"$ParticipantName\"}) by (topic_name, type_name)"
      },
      {
       "expr": "max(dds_data_reader_serialized_sample_min_size_bytes{participant_name=\"$ParticipantName\"}) by (topic_name, type_name)"
      },
      {
       "expr": "max(dds_data_reader_serialized_sample_max_size_bytes{participant_name=\"$ParticipantName\"}) by (topic_name, type_name)"
      },
      {
       "expr": "max(dds_data_reader_serialized_key_max_size_bytes{participant_name=\"$ParticipantName\"}) by (topic_name, type_name)"
      }
     ]
    },
    {
     "title": "Local Entities",
     "type": "table",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "count by (participant_name) (dds_data_reader_serialized_sample_max_size_bytes{participant_name=\"$ParticipantName\"})",
       "legendFormat": "Local Readers"
      },
      {
       "expr": "count by (participant_name) (dds_data_writer_serialized_sample_max_size_bytes{participant_name=\"$ParticipantName\"})",
       "legendFormat": "Local Writers"
      }
     ]
    },
    {
     "title": "Remote Entities",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "dds_domain_participant_remote_participant_count{participant_name=\"$ParticipantName\"}",
       "legendFormat": "Remote Participants"
      },
      {
       "expr": "dds_domain_participant_remote_reader_count{participant_name=\"$ParticipantName\"}",
       "legendFormat": "Remote Readers"
      },
      {
       "expr": "dds_domain_participant_remote_writer_count{participant_name=\"$ParticipantName\"}",
       "legendFormat": "Remote Writers"
      }
     ]
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(dds_domain_participant_user_cpu_time_nanoseconds{participant_name=\"$ParticipantName\"}[1m]) / 100000000",
     "legendFormat": "1 Minute Average {{ participant_name }}"
    },
    {
     "expr": "rate(dds_domain_participant_user_cpu_time_nanoseconds{participant_name=\"$ParticipantName\"}[5m]) / 100000000",
     "legendFormat": "5 Minute Average {{ participant_name }}"
    },
    {
     "expr": "rate(dds_domain_participant_user_cpu_time_nanoseconds{participant_name=\"$ParticipantName\"}[15m]) / 100000000",
     "legendFormat": "15 Minute Average {{ participant_name }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "dds_domain_participant_total_memory_bytes{participant_name=\"$ParticipantName\"}",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "dds_domain_participant_physical_memory_bytes{participant_name=\"$ParticipantName\"}",
     "legendFormat": "Memory Allocated"
    }
   ]
  },
  {
   "title": "Data Writers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data Writer Samples",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Samples/s" }
     ],
     "targets": [
      {
       "expr": "rate(dds_data_writer_protocol_status_pushed_sample_count{participant_name=\"$ParticipantName\"}[1m]) + rate(dds_data_writer_protocol_status_pulled_sample_count{participant_name=\"$ParticipantName\"}[1m])",
       "legendFormat": "{{ publication_name }} Samples/s"
      },
      {
       "expr": "rate(dds_data_writer_protocol_status_pushed_sample_bytes{participant_name=\"$ParticipantName\"}[1m]) + rate(dds_data_writer_protocol_status_pulled_sample_bytes{participant_name=\"$ParticipantName\"}[1m])",
       "legendFormat": "{{ publication_name }} Bytes/s"
      }
     ]
    },
    {
     "title": "Data Writer Heartbeats",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "Count/s" }
     ],
     "targets": [
      {
       "expr": "rate(dds_data_writer_protocol_status_sent_heartbeat_count{participant_name=\"$ParticipantName\"}[1m])",
       "legendFormat": "{{ publication_name }} Count/s"
      },
      {
       "expr": "rate(dds_data_writer_protocol_status_sent_heartbeat_bytes{participant_name=\"$ParticipantName\"}[1m])",
       "legendFormat": "{{ publication_name }} Bytes/s"
      }
     ]
    }
   ]
  },
  {
   "title": "Data Readers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data Reader Samples",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "Count/s" }
     ],
     "targets": [
      {
       "expr": "rate(dds_data_reader_protocol_status_received_sample_count{participant_name=\"$ParticipantName\"}[1m])",
       "legendFormat": "{{ subscription_name }} Count/s"
      },
      {
       "expr": "rate(dds_data_reader_protocol_status_received_sample_bytes{participant_name=\"$ParticipantName\"}[1m])",
       "legendFormat": "{{ subscription_name }} Bytes/s"
      }
     ]
    },
    {
     "title": "Data Reader Heartbeats",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "Count/s" }
     ],
     "targets": [
      {
       "expr": "rate(dds_data_reader_protocol_status_received_heartbeat_count{participant_name=\"$ParticipantName\"}[1m])",
       "legendFormat": "{{ subscription_name }} Count/s"
      },
      {
       "expr": "rate(dds_data_reader_protocol_status_received_heartbeat_bytes{participant_name=\"$ParticipantName\"}[1m])",
       "legendFormat": "{{ subscription_name }} Bytes/s"
      }
     ]
    }
   ]
  },
  {
   "title": "Error Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sample Lost / Rejected Rates",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(dds_data_writer_protocol_status_rejected_sample_count{participant_name=\"$ParticipantName\"}[1m])",
       "legendFormat": "Data Writer Rejected ({{ publication_name }})"
      },
      {
       "expr": "rate(dds_data_reader_sample_lost_status_total_count{participant_name=\"$ParticipantName\"}[1m])",
       "legendFormat": "Data Reader Lost ({{ subscription_name }})"
      },
      {
       "expr": "rate(dds_data_reader_sample_rejected_status_total_count{participant_name=\"$ParticipantName\"}[1m])",
       "legendFormat": "Data Reader Rejected ({{ subscription_name }})"
      }
     ]
    },
    {
     "title": "NACK Rates",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(dds_data_writer_protocol_status_received_nack_count{participant_name=\"$ParticipantName\"}[1m])",
       "legendFormat": "{{ publication_name }}"
      },
      {
       "expr": "rate(dds_data_reader_protocol_status_sent_nack_count{participant_name=\"$ParticipantName\"}[1m])",
       "legendFormat": "{{ subscription_name }}"
      }
     ]
    },
    {
     "title": "Deadline Missed Rates",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(dds_data_writer_offered_deadline_missed_status_total_count{participant_name=\"$ParticipantName\"}[1m])",
       "legendFormat": "Data Writer ({{ publication_name }})"
      },
      {
       "expr": "rate(dds_data_reader_requested_deadline_missed_status_total_count{participant_name=\"$ParticipantName\"}[1m])",
       "legendFormat": "Data Reader ({{ subscription_name }})"
      }
     ]
    }
   ]
  },
  {
   "title": "Incompatibilities",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Incompatiblities",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "dds_topic_inconsistent_topic_status_total_count{participant_name=\"$ParticipantName\"}",
       "legendFormat": "Inconsistent Topics"
      },
      {
       "expr": "sum(dds_data_writer_offered_incompatible_qos_status_total_count{participant_name=\"$ParticipantName\"})",
       "legendFormat": "Offered incompatible QoS"
      },
      {
       "expr": "sum(dds_data_reader_requested_incompatible_qos_status_total_count{participant_name=\"$ParticipantName\"})",
       "legendFormat": "Requested incompatible QoS"
      }
     ]
    }
   ]
  }
 ]
}