{
 "title": "Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Monitored Entities",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(dds_domain_participant_user_cpu_time_nanoseconds)",
     "legendFormat": "Domain Participants"
    },
    {
     "expr": "count(dds_data_writer_serialized_sample_max_size_bytes)",
     "legendFormat": "Data Writers"
    },
    {
     "expr": "count(dds_data_reader_serialized_sample_max_size_bytes)",
     "legendFormat": "Data Readers"
    },
    {
     "expr": "count(dds_routing_service_state)",
     "legendFormat": "Routing Services"
    }
   ]
  },
  {
   "title": "Sample Lost / Rejected Rate",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dds_data_writer_protocol_status_rejected_sample_count[1m])",
     "legendFormat": "{{ participant_name }}/{{ publication_name }} (Writer Rejected)"
    },
    {
     "expr": "rate(dds_data_reader_sample_lost_status_total_count[1m])",
     "legendFormat": "{{ participant_name }}/{{ subscription_name}} (Reader Lost)"
    },
    {
     "expr": "rate(dds_data_reader_sample_rejected_status_total_count[1m])",
     "legendFormat": "{{ participant_name }}/{{ subscription_name }} (Reader Rejected)"
    }
   ]
  },
  {
   "title": "NACK Rate",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dds_data_writer_protocol_status_received_nack_count[1m])",
     "legendFormat": "{{ participant_name }}/{{ publication_name }}"
    },
    {
     "expr": "rate(dds_data_reader_protocol_status_sent_nack_count[1m])",
     "legendFormat": "{{ participant_name }}/{{ subscription_name }}"
    }
   ]
  },
  {
   "title": "Deadline Missed Rate",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dds_data_writer_offered_deadline_missed_status_total_count[1m])",
     "legendFormat": "{{ participant_name }}/{{ publication_name }}"
    },
    {
     "expr": "rate(dds_data_reader_requested_deadline_missed_status_total_count[1m])",
     "legendFormat": "{{ participant_name }}/{{ subscription_name }}"
    }
   ]
  }
 ]
}