{
 "title": "Routing Service",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "RoutingService",
    "query": "label_values(dds_routing_service_process_uptime_seconds, routing_service)"
   },
   {
    "name": "DomainRoute",
    "query": "label_values(dds_routing_service_domain_route_state{routing_service=\"$RoutingService\"}, domain_route)"
   },
   {
    "name": "Session",
    "query": "label_values(dds_routing_service_session_state{routing_service=\"$RoutingService\", domain_route=\"$DomainRoute\"}, session)"
   },
   {
    "name": "AutoRoute",
    "query": "label_values(dds_routing_service_auto_route_state{routing_service=\"$RoutingService\", domain_route=\"$DomainRoute\", session=\"$Session\"}, auto_route)"
   },
   {
    "name": "Route",
    "query": "label_values(dds_routing_service_route_state{routing_service=\"$RoutingService\", domain_route=\"$DomainRoute\", session=\"$Session\"}, route)"
   }
  ]
 },
 "panels": [
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "dds_routing_service_process_cpu_usage_percentage{routing_service=~\"$RoutingService\"}",
     "legendFormat": "Process"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "dds_routing_service_process_physical_memory_kilobytes{routing_service=~\"$RoutingService\"}",
     "legendFormat": "Memory Allocated"
    }
   ]
  },
  { "title": "Domain Routes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Sample Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Samples/s" }
   ],
   "targets": [
    {
     "expr": "dds_routing_service_domain_route_in_samples_per_second{routing_service=~\"$RoutingService\", domain_route=~\"$DomainRoute\"}",
     "legendFormat": "{{ domain_route }} (IN)"
    },
    {
     "expr": "dds_routing_service_domain_route_out_samples_per_second{routing_service=~\"$RoutingService\", domain_route=~\"$DomainRoute\"}",
     "legendFormat": "{{ domain_route }} (OUT)"
    }
   ]
  },
  {
   "title": "Data Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "dds_routing_service_domain_route_in_bytes_per_second{routing_service=~\"$RoutingService\", domain_route=~\"$DomainRoute\"}",
     "legendFormat": "{{ domain_route }} (IN)"
    },
    {
     "expr": "dds_routing_service_domain_route_out_bytes_per_second{routing_service=~\"$RoutingService\", domain_route=~\"$DomainRoute\"}",
     "legendFormat": "{{ domain_route }} (OUT)"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "ms", "label": "Latency" }
   ],
   "targets": [
    {
     "expr": "dds_routing_service_domain_route_latency_milliseconds{routing_service=~\"$RoutingService\", domain_route=~\"$DomainRoute\"}",
     "legendFormat": "{{ domain_route }} (IN)"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sample Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "Samples/s" }
     ],
     "targets": [
      {
       "expr": "dds_routing_service_session_in_samples_per_second{routing_service=~\"$RoutingService\", domain_route=~\"$DomainRoute\", session=~\"$Session\"}",
       "legendFormat": "{{ domain_route }}/{{ session }} (IN)"
      },
      {
       "expr": "dds_routing_service_session_out_samples_per_second{routing_service=~\"$RoutingService\", domain_route=~\"$DomainRoute\", session=~\"$Session\"}",
       "legendFormat": "{{ domain_route }}/{{ session }} (OUT)"
      }
     ]
    },
    {
     "title": "Data Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "dds_routing_service_session_in_bytes_per_second{routing_service=~\"$RoutingService\", domain_route=~\"$DomainRoute\", session=~\"$Session\"}",
       "legendFormat": "{{ domain_route }}/{{ session }} (IN)"
      },
      {
       "expr": "dds_routing_service_session_out_bytes_per_second{routing_service=~\"$RoutingService\", domain_route=~\"$DomainRoute\", session=~\"$Session\"}",
       "legendFormat": "{{ domain_route }}/{{ session }} (OUT)"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "ms", "label": "Latency" }
     ],
     "targets": [
      {
       "expr": "dds_routing_service_session_latency_milliseconds{routing_service=~\"$RoutingService\", domain_route=~\"$DomainRoute\", session=~\"$Session\"}",
       "legendFormat": "{{ domain_route }}/{{ session }} (IN)"
      }
     ]
    }
   ]
  },
  {
   "title": "Auto Routes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sample Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Samples/s" }
     ],
     "targets": [
      {
       "expr": "dds_routing_service_auto_route_in_samples_per_second{routing_service=~\"$RoutingService\", domain_route=~\"$DomainRoute\", session=~\"$Session\", auto_route=~\"$AutoRoute\"}",
       "legendFormat": "{{ domain_route }}/{{ session }}/{{ auto_route }} (IN)"
      },
      {
       "expr": "dds_routing_service_auto_route_out_samples_per_second{routing_service=~\"$RoutingService\", domain_route=~\"$DomainRoute\", session=~\"$Session\", auto_route=~\"$AutoRoute\"}",
       "legendFormat": "{{ domain_route }}/{{ session }}/{{ auto_route }} (OUT)"
      }
     ]
    },
    {
     "title": "Data Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "dds_routing_service_auto_route_in_bytes_per_second{routing_service=~\"$RoutingService\", domain_route=~\"$DomainRoute\", session=~\"$Session\", auto_route=~\"$AutoRoute\"}",
       "legendFormat": "{{ domain_route }}/{{ session }}/{{ auto_route }} (IN)"
      },
      {
       "expr": "dds_routing_service_auto_route_out_bytes_per_second{routing_service=~\"$RoutingService\", domain_route=~\"$DomainRoute\", session=~\"$Session\", auto_route=~\"$AutoRoute\"}",
       "legendFormat": "{{ domain_route }}/{{ session }}/{{ auto_route }} (OUT)"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "ms", "label": "Latency" }
     ],
     "targets": [
      {
       "expr": "dds_routing_service_auto_route_latency_milliseconds{routing_service=~\"$RoutingService\", domain_route=~\"$DomainRoute\", session=~\"$Session\", auto_route=~\"$AutoRoute\"}",
       "legendFormat": "{{ domain_route }}/{{ session }}/{{ auto_route }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Routes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sample Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short", "label": "Samples/s" }
     ],
     "targets": [
      {
       "expr": "dds_routing_service_route_in_samples_per_second{routing_service=~\"$RoutingService\", domain_route=~\"$DomainRoute\", session=~\"$Session\", route=~\"$Route\"}",
       "legendFormat": "{{ domain_route }}/{{ session }}/{{ route }} (IN)"
      },
      {
       "expr": "dds_routing_service_route_out_samples_per_second{routing_service=~\"$RoutingService\", domain_route=~\"$DomainRoute\", session=~\"$Session\", route=~\"$Route\"}",
       "legendFormat": "{{ domain_route }}/{{ session }}/{{ route }} (OUT)"
      }
     ]
    },
    {
     "title": "Data Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "dds_routing_service_route_in_bytes_per_second{routing_service=~\"$RoutingService\", domain_route=~\"$DomainRoute\", session=~\"$Session\", route=~\"$Route\"}",
       "legendFormat": "{{ domain_route }}/{{ session }}/{{ route }} (IN)"
      },
      {
       "expr": "dds_routing_service_route_out_bytes_per_second{routing_service=~\"$RoutingService\", domain_route=~\"$DomainRoute\", session=~\"$Session\", route=~\"$Route\"}",
       "legendFormat": "{{ domain_route }}/{{ session }}/{{ route }} (OUT)"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
     "yaxes": [
      { "format": "ms", "label": "Latency" }
     ],
     "targets": [
      {
       "expr": "dds_routing_service_route_latency_milliseconds{routing_service=~\"$RoutingService\", domain_route=~\"$DomainRoute\", session=~\"$Session\", route=~\"$Route\"}",
       "legendFormat": "{{ domain_route }}/{{ session }}/{{ route }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Inputs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sample Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Samples/s" }
     ],
     "targets": [
      {
       "expr": "dds_routing_service_input_samples_per_second{routing_service=~\"$RoutingService\", domain_route=~\"$DomainRoute\", session=~\"$Session\", route=~\"$Route\"}",
       "legendFormat": "{{ domain_route }}/{{ session }}/{{ route }}/{{ input }} (IN)"
      }
     ]
    },
    {
     "title": "Data Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "dds_routing_service_input_bytes_per_second{routing_service=~\"$RoutingService\", domain_route=~\"$DomainRoute\", session=~\"$Session\", route=~\"$Route\"}",
       "legendFormat": "{{ domain_route }}/{{ session }}/{{ route }}/{{ input }} (IN)"
      }
     ]
    }
   ]
  },
  {
   "title": "Outputs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sample Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "Samples/s" }
     ],
     "targets": [
      {
       "expr": "dds_routing_service_output_samples_per_second{routing_service=~\"$RoutingService\", domain_route=~\"$DomainRoute\", session=~\"$Session\", route=~\"$Route\"}",
       "legendFormat": "{{ domain_route }}/{{ session }}/{{ route }}/{{ output }} (IN)"
      }
     ]
    },
    {
     "title": "Data Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "dds_routing_service_output_bytes_per_second{routing_service=~\"$RoutingService\", domain_route=~\"$DomainRoute\", session=~\"$Session\", route=~\"$Route\"}",
       "legendFormat": "{{ domain_route }}/{{ session }}/{{ route }}/{{ input }} (IN)"
      }
     ]
    }
   ]
  },
  {
   "title": "States",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Domain Routes",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "max(dds_routing_service_domain_route_state{routing_service=~\"$RoutingService\", domain_route=~\"$DomainRoute\"}) by (routing_service, domain_route)"
      }
     ]
    },
    {
     "title": "Sessions",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "max(dds_routing_service_session_state{routing_service=~\"$RoutingService\", domain_route=~\"$DomainRoute\", session=~\"$Session\"}) by (routing_service, domain_route, session)"
      }
     ]
    },
    {
     "title": "Auto Routes",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "max(dds_routing_service_auto_route_state{routing_service=~\"$RoutingService\", domain_route=~\"$DomainRoute\", session=~\"$Session\", auto_route=~\"$AutoRoute\"}) by (routing_service, domain_route, session, auto_route)"
      }
     ]
    },
    {
     "title": "Routes",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "max(dds_routing_service_route_state{routing_service=~\"$RoutingService\", domain_route=~\"$DomainRoute\", session=~\"$Session\", route=~\"$Route\"}) by (routing_service, domain_route, session, route)"
      }
     ]
    },
    {
     "title": "Inputs",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "max(dds_routing_service_input_state{routing_service=\"$RoutingService\"}) by (routing_service, domain_route, session, route, input)"
      }
     ]
    },
    {
     "title": "Outputs",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "max(dds_routing_service_output_state{routing_service=\"$RoutingService\"}) by (routing_service, domain_route, session, route, input)"
      }
     ]
    }
   ]
  }
 ]
}